/* eslint-disable @next/next/no-page-custom-font */
import Homepage from "@/page-component/Homepage";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Gastro App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Homepage />
      </main>
    </>
  );
}
